services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5400:5432"

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  pgdata:
